//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
namespace OSATypes
{


    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.1.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    //[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class StartVelocity
    {

        private string xField;

        private string yField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string X
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }
    }
    [XmlRoot(ElementName = "CharacterTemplate", Namespace = "", IsNullable = false)]
    public partial class CharacterTemplate : RoomObjectTemplate { }

    [XmlRoot(ElementName = "DoorTemplate", Namespace = "", IsNullable = false)]
    public partial class DoorTemplate : RoomObjectTemplate { }

    [XmlRoot(ElementName = "CollectibleTemplate", Namespace = "", IsNullable = false)]
    public partial class CollectibleTemplate : RoomObjectTemplate { }


    [XmlRoot(ElementName = "ObstacleTemplate", Namespace = "", IsNullable = false)]
    public partial class ObstacleTemplate : RoomObjectTemplate { }


    [XmlRoot(ElementName = "DirectorTemplate", Namespace = "", IsNullable = false)]
    public partial class DirectorTemplate : RoomObjectTemplate { }


    [XmlRoot(ElementName = "SpawnPointTemplate", Namespace = "", IsNullable = false)]
    public partial class SpawnPointTemplate : RoomObjectTemplate { }


    [XmlRoot(ElementName = "SpeakerTemplate", Namespace = "", IsNullable = false)]
    public partial class SpeakerTemplate : RoomObjectTemplate { }


    [XmlRoot(ElementName = "MusicPointTemplate", Namespace = "", IsNullable = false)]
    public partial class MusicPointTemplate : RoomObjectTemplate { }


    [XmlRoot(ElementName = "SwitchTemplate", Namespace = "", IsNullable = false)]
    public partial class SwitchTemplate : RoomObjectTemplate { }


    [XmlRoot(ElementName = "EnemyTemplate", Namespace = "", IsNullable = false)]
    public partial class EnemyTemplate : RoomObjectTemplate { }


    [XmlRoot(ElementName = "ProjectileTemplate", Namespace = "", IsNullable = false)]
    public partial class ProjectileTemplate : RoomObjectTemplate { }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RoomObjectTemplate
    {

        private TemplateSize[] sizeField;

        private StartVelocity[] startVelocityField;

        private TemplateSurface[] leftField;

        private TemplateSurface[] topField;

        private TemplateSurface[] rightField;

        private TemplateSurface[] bottomField;

        private TemplatePower[] powerField;

        private TemplateAudio[] audioField;

        private TemplateRotationGridOffset[] rotationGridOffsetField;

        private TemplateVelocity[] velocityField;

        private TemplateMovementProvider[] movementProviderField;

        private TemplateShootInformation[] shootInformationField;

        private TemplateLock[] lockField;

        private string showCarryField;

        private string typeField;

        private string directionField;

        private string timePerRevolutionField;

        private string verticalAlignmentField;

        private string renderModeField;

        private string requiresInteractionField;

        private string isSpawnPointOnly;

        private string isDeadly;

        private string offenseField;

        private string defenseField;

        private string frictionField;

        private string musicField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Size", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TemplateSize[] Size
        {
            get
            {
                return this.sizeField;
            }
            set
            {
                this.sizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StartVelocity")]
        public StartVelocity[] StartVelocity
        {
            get
            {
                return this.startVelocityField;
            }
            set
            {
                this.startVelocityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Left", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TemplateSurface[] Left
        {
            get
            {
                return this.leftField;
            }
            set
            {
                this.leftField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Top", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TemplateSurface[] Top
        {
            get
            {
                return this.topField;
            }
            set
            {
                this.topField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Right", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TemplateSurface[] Right
        {
            get
            {
                return this.rightField;
            }
            set
            {
                this.rightField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Bottom", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TemplateSurface[] Bottom
        {
            get
            {
                return this.bottomField;
            }
            set
            {
                this.bottomField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Power", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TemplatePower[] Power
        {
            get
            {
                return this.powerField;
            }
            set
            {
                this.powerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Audio", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TemplateAudio[] Audio
        {
            get
            {
                return this.audioField;
            }
            set
            {
                this.audioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RotationGridOffset", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TemplateRotationGridOffset[] RotationGridOffset
        {
            get
            {
                return this.rotationGridOffsetField;
            }
            set
            {
                this.rotationGridOffsetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Velocity", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TemplateVelocity[] Velocity
        {
            get
            {
                return this.velocityField;
            }
            set
            {
                this.velocityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MovementProvider", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TemplateMovementProvider[] MovementProvider
        {
            get
            {
                return this.movementProviderField;
            }
            set
            {
                this.movementProviderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShootInformation", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TemplateShootInformation[] ShootInformation
        {
            get
            {
                return this.shootInformationField;
            }
            set
            {
                this.shootInformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Lock", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TemplateLock[] Lock
        {
            get
            {
                return this.lockField;
            }
            set
            {
                this.lockField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ShowCarry
        {
            get
            {
                return this.showCarryField;
            }
            set
            {
                this.showCarryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TimePerRevolution
        {
            get
            {
                return this.timePerRevolutionField;
            }
            set
            {
                this.timePerRevolutionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VerticalAlignment
        {
            get
            {
                return this.verticalAlignmentField;
            }
            set
            {
                this.verticalAlignmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RenderMode
        {
            get
            {
                return this.renderModeField;
            }
            set
            {
                this.renderModeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RequiresInteraction
        {
            get
            {
                return this.requiresInteractionField;
            }
            set
            {
                this.requiresInteractionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IsSpawnPointOnly
        {
            get
            {
                return this.isSpawnPointOnly;
            }
            set
            {
                this.isSpawnPointOnly = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IsDeadly
        {
            get
            {
                return this.isDeadly;
            }
            set
            {
                this.isDeadly = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Offense
        {
            get
            {
                return this.offenseField;
            }
            set
            {
                this.offenseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Defense
        {
            get
            {
                return this.defenseField;
            }
            set
            {
                this.defenseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Friction
        {
            get
            {
                return this.frictionField;
            }
            set
            {
                this.frictionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Music
        {
            get
            {
                return this.musicField;
            }
            set
            {
                this.musicField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TemplateSize
    {

        private string widthField;

        private string heightField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TemplateSurface
    {

        private string isSolidField;

        private string frictionField;

        private string isDeadlyField;

        private string dieField;

        private string velocityField;

        private string tangentSpeedField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IsSolid
        {
            get
            {
                return this.isSolidField;
            }
            set
            {
                this.isSolidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Friction
        {
            get
            {
                return this.frictionField;
            }
            set
            {
                this.frictionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IsDeadly
        {
            get
            {
                return this.isDeadlyField;
            }
            set
            {
                this.isDeadlyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Die
        {
            get
            {
                return this.dieField;
            }
            set
            {
                this.dieField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Velocity
        {
            get
            {
                return this.velocityField;
            }
            set
            {
                this.velocityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TangentSpeed
        {
            get
            {
                return this.tangentSpeedField;
            }
            set
            {
                this.tangentSpeedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TemplatePower
    {

        private string ownerPathField;

        private string canFlyField;

        private string canAccelerateFromTileField;

        private string offenseField;

        private string defenseField;

        private string maxHorizontalSpeedFactorField;

        private string gravityField;

        private string runRightField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OwnerPath
        {
            get
            {
                return this.ownerPathField;
            }
            set
            {
                this.ownerPathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CanFly
        {
            get
            {
                return this.canFlyField;
            }
            set
            {
                this.canFlyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CanAccelerateFromTile
        {
            get
            {
                return this.canAccelerateFromTileField;
            }
            set
            {
                this.canAccelerateFromTileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Offense
        {
            get
            {
                return this.offenseField;
            }
            set
            {
                this.offenseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Defense
        {
            get
            {
                return this.defenseField;
            }
            set
            {
                this.defenseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MaxHorizontalSpeedFactor
        {
            get
            {
                return this.maxHorizontalSpeedFactorField;
            }
            set
            {
                this.maxHorizontalSpeedFactorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Gravity
        {
            get
            {
                return this.gravityField;
            }
            set
            {
                this.gravityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RunRight
        {
            get
            {
                return this.runRightField;
            }
            set
            {
                this.runRightField = value;
            }
        }
    }

        /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class TemplateAudio
    {

        private TemplateAudioCue[] audioItem;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cue")]
        public TemplateAudioCue[] Cue
        {
            get
            {
                return this.audioItem;
            }
            set
            {
                this.audioItem = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TemplateAudioCue
    {

        private string nameField;

        private string eventField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Event
        {
            get
            {
                return this.eventField;
            }
            set
            {
                this.eventField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TemplateRotationGridOffset
    {

        private string xField;

        private string yField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string X
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TemplateVelocity
    {

        private string xField;

        private string yField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string X
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TemplateMovementProvider
    {

        private string nameField;

        private string maxHorizontalSpeedField;

        private string intelligenceAlgorithmField;

        private string deathDurationField;

        private string startOrientationField;

        private string gravityField;

        private string jumpSpeedField;

        private string maxDefaultJumpHeightField;

        private string maxWallJumpHeightField;

        private string maxVerticalSpeedField;

        private string horizontalAccelerationField;

        private string flyAccelerationField;

        private string deathStartVerticalSpeedField;

		private string timePerRevolutionField;

		private string directionField;
		
		private Conditions[] conditionField;


        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MaxHorizontalSpeed
        {
            get
            {
                return this.maxHorizontalSpeedField;
            }
            set
            {
                this.maxHorizontalSpeedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IntelligenceAlgorithm
        {
            get
            {
                return this.intelligenceAlgorithmField;
            }
            set
            {
                this.intelligenceAlgorithmField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DeathDuration
        {
            get
            {
                return this.deathDurationField;
            }
            set
            {
                this.deathDurationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StartOrientation
        {
            get
            {
                return this.startOrientationField;
            }
            set
            {
                this.startOrientationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Gravity
        {
            get
            {
                return this.gravityField;
            }
            set
            {
                this.gravityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string JumpSpeed
        {
            get
            {
                return this.jumpSpeedField;
            }
            set
            {
                this.jumpSpeedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MaxDefaultJumpHeight
        {
            get
            {
                return this.maxDefaultJumpHeightField;
            }
            set
            {
                this.maxDefaultJumpHeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MaxWallJumpHeight
        {
            get
            {
                return this.maxWallJumpHeightField;
            }
            set
            {
                this.maxWallJumpHeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MaxVerticalSpeed
        {
            get
            {
                return this.maxVerticalSpeedField;
            }
            set
            {
                this.maxVerticalSpeedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HorizontalAcceleration
        {
            get
            {
                return this.horizontalAccelerationField;
            }
            set
            {
                this.horizontalAccelerationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FlyAcceleration
        {
            get
            {
                return this.flyAccelerationField;
            }
            set
            {
                this.flyAccelerationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DeathStartVerticalSpeed
        {
            get
            {
                return this.deathStartVerticalSpeedField;
            }
            set
            {
                this.deathStartVerticalSpeedField = value;
            }
        }

		/// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
		public string TimePerRevolution
        {
            get
            {
				return this.timePerRevolutionField;
            }
            set
            {
				this.timePerRevolutionField = value;
            }
        }

		/// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
		public string Direction
        {
            get
            {
				return this.directionField;
            }
            set
            {
				this.directionField = value;
            }
        }		

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Conditions", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Conditions[] Conditions
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TemplateMovementProviderCondition
    {

        private string hasField;

        private string itemField;

        private string quantityField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Has
        {
            get
            {
                return this.hasField;
            }
            set
            {
                this.hasField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TemplateShootInformation
    {

        private TemplateShootInformationObject[] objectField;

        private TemplateShootInformationStartPosition[] startPositionField;

        private StartVelocity[] startVelocityField;

        private string durationField;

        private string minWaitField;

        private string maxWaitField;

        private string flipOnNegativeXField;

        private string flipOnNegativeYField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Object", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TemplateShootInformationObject[] Object
        {
            get
            {
                return this.objectField;
            }
            set
            {
                this.objectField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StartPosition", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TemplateShootInformationStartPosition[] StartPosition
        {
            get
            {
                return this.startPositionField;
            }
            set
            {
                this.startPositionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StartVelocity")]
        public StartVelocity[] StartVelocity
        {
            get
            {
                return this.startVelocityField;
            }
            set
            {
                this.startVelocityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MinWait
        {
            get
            {
                return this.minWaitField;
            }
            set
            {
                this.minWaitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MaxWait
        {
            get
            {
                return this.maxWaitField;
            }
            set
            {
                this.maxWaitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FlipOnNegativeX
        {
            get
            {
                return this.flipOnNegativeXField;
            }
            set
            {
                this.flipOnNegativeXField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FlipOnNegativeY
        {
            get
            {
                return this.flipOnNegativeYField;
            }
            set
            {
                this.flipOnNegativeYField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TemplateShootInformationObject
    {

        private string pathField;

        private string maxCountField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MaxCount
        {
            get
            {
                return this.maxCountField;
            }
            set
            {
                this.maxCountField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TemplateShootInformationStartPosition
    {

        private string xField;

        private string yField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string X
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TemplateLock
    {

        private string requiredItemField;

        private string typeField;

        private string messageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RequiredItem
        {
            get
            {
                return this.requiredItemField;
            }
            set
            {
                this.requiredItemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [XmlRoot(ElementName = "", Namespace = "", IsNullable = false)]
    public partial class NewDataSet
    {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CharacterTemplate", typeof(CharacterTemplate))]
        [System.Xml.Serialization.XmlElementAttribute("DoorTemplate", typeof(DoorTemplate))]
        [System.Xml.Serialization.XmlElementAttribute("CollectibleTemplate", typeof(RoomObjectTemplate))]
        [System.Xml.Serialization.XmlElementAttribute("ObstacleTemplate", typeof(RoomObjectTemplate))]
        [System.Xml.Serialization.XmlElementAttribute("DirectorTemplate", typeof(RoomObjectTemplate))]
        [System.Xml.Serialization.XmlElementAttribute("SpawnPointTemplate", typeof(RoomObjectTemplate))]
        [System.Xml.Serialization.XmlElementAttribute("SpeakerTemplate", typeof(RoomObjectTemplate))]
        [System.Xml.Serialization.XmlElementAttribute("MusicPointTemplate", typeof(RoomObjectTemplate))]
        [System.Xml.Serialization.XmlElementAttribute("SwitchTemplate", typeof(RoomObjectTemplate))]
        [System.Xml.Serialization.XmlElementAttribute("EnemyTemplate", typeof(RoomObjectTemplate))]
        [System.Xml.Serialization.XmlElementAttribute("ProjectileTemplate", typeof(RoomObjectTemplate))]
        [XmlChoiceIdentifier("RoomObjectTypesArray")]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        public RoomObjectTypes[] RoomObjectTypesArray;

    }

    public enum RoomObjectTypes
    {
        CharacterTemplate,
        DoorTemplate,
        CollectibleTemplate,
        ObstacleTemplate,
        DirectorTemplate,
        SpawnPointTemplate,
        SpeakerTemplate,
        MusicPointTemplate,
        SwitchTemplate,
        EnemyTemplate,
        ProjectileTemplate
    }
}