//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Collections.Generic;
namespace OSATypes
{
    public enum ContainerObjectTypes
    {
        Size,
        Lighting,
        Backgrounds,
        TileGrids,
        Doors,
        Collectibles,
        Obstacles,
        Directors,
        SpawnPoints,
        Speakers,
        MusicPoints,
        Switches,
        Enemies
    }

    public enum ObjectTypes
    {
        Door,
        Collectible,
        Obstacle,
        Director,
        SpawnPoint,
        Speaker,
        MusicPoint,
        Switch,
        Enemy
    }
    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.1.
    // 

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Room
    {
        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Size", typeof(RoomSize))]
        [System.Xml.Serialization.XmlElementAttribute("Lighting", typeof(RoomLighting))]
        [System.Xml.Serialization.XmlElementAttribute("Backgrounds", typeof(RoomBackgrounds))]
        [System.Xml.Serialization.XmlElementAttribute("TileGrids", typeof(RoomTileGrids))]
        [System.Xml.Serialization.XmlElementAttribute("Doors", typeof(RoomObject))]
        [System.Xml.Serialization.XmlElementAttribute("Collectibles", typeof(RoomObject))]
        [System.Xml.Serialization.XmlElementAttribute("Obstacles", typeof(RoomObject))]
        [System.Xml.Serialization.XmlElementAttribute("Directors", typeof(RoomObject))]
        [System.Xml.Serialization.XmlElementAttribute("SpawnPoints", typeof(RoomObject))]
        [System.Xml.Serialization.XmlElementAttribute("Speakers", typeof(RoomObject))]
        [System.Xml.Serialization.XmlElementAttribute("MusicPoints", typeof(RoomObject))]
        [System.Xml.Serialization.XmlElementAttribute("Switches", typeof(RoomObject))]
        [System.Xml.Serialization.XmlElementAttribute("Enemies", typeof(RoomObject))]
        [XmlChoiceIdentifier("ContainerObjectTypesArray")]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        public ContainerObjectTypes[] ContainerObjectTypesArray;

    }

    #region Room
 
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RoomSize
    {

        private string widthField;

        private string heightField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Width")]
        public string Width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Height")]
        public string Height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RoomLighting
    {

        private List<RoomLightingStart> startField;

        private List<RoomLightingFinish> finishField;

        private string axisField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Start")]
        public List<RoomLightingStart> Start
        {
            get
            {
                return this.startField;
            }
            set
            {
                this.startField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Finish")]
        public List<RoomLightingFinish> Finish
        {
            get
            {
                return this.finishField;
            }
            set
            {
                this.finishField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Axis")]
        public string Axis
        {
            get
            {
                return this.axisField;
            }
            set
            {
                this.axisField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RoomLightingStart
    {

        private List<OSATypes.Color> colorField;

        private string gridPositionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Color")]
        public List<OSATypes.Color> Color
        {
            get
            {
                return this.colorField;
            }
            set
            {
                this.colorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("GridPosition")]
        public string GridPosition
        {
            get
            {
                return this.gridPositionField;
            }
            set
            {
                this.gridPositionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RoomLightingFinish
    {

        private List<Color> colorField;

        private string gridPositionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Color")]
        public List<Color> Color
        {
            get
            {
                return this.colorField;
            }
            set
            {
                this.colorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("GridPosition")]
        public string GridPosition
        {
            get
            {
                return this.gridPositionField;
            }
            set
            {
                this.gridPositionField = value;
            }
        }
    }



    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Color
    {

        private string redField;

        private string greenField;

        private string blueField;

        private string alphaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Red")]
        public string Red
        {
            get
            {
                return this.redField;
            }
            set
            {
                this.redField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Green")]
        public string Green
        {
            get
            {
                return this.greenField;
            }
            set
            {
                this.greenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Blue")]
        public string Blue
        {
            get
            {
                return this.blueField;
            }
            set
            {
                this.blueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Alpha")]
        public string Alpha
        {
            get
            {
                return this.alphaField;
            }
            set
            {
                this.alphaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RoomBackgrounds
    {

        private List<RoomBackgroundsBackground> background;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Background")]
        public List<RoomBackgroundsBackground> Background
        {
            get
            {
                return this.background;
            }
            set
            {
                this.background = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RoomBackgroundsBackground
    {

        private List<RoomBackgroundsBackgroundScrollRate> scrollRateField;

        private string pathField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ScrollRate")]
        public List<RoomBackgroundsBackgroundScrollRate> ScrollRate
        {
            get
            {
                return this.scrollRateField;
            }
            set
            {
                this.scrollRateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Path")]
        public string Path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RoomBackgroundsBackgroundScrollRate
    {

        private string xField;

        private string yField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("X")]
        public string X
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Y")]
        public string Y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RoomTileGrids
    {

        private List<RoomTileGridsTileGrid> tileGrid;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TileGrid")]
        public List<RoomTileGridsTileGrid> TileGrid
        {
            get
            {
                return this.tileGrid;
            }
            set
            {
                this.tileGrid = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RoomTileGridsTileGrid
    {

        private List<RoomTileGridsTileGridGridSize> gridSizeField;

        private List<RoomTileGridsTileGridRows> rowsField;

        private string isActiveField;

        private string tileSetField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GridSize")]
        public List<RoomTileGridsTileGridGridSize> GridSize
        {
            get
            {
                return this.gridSizeField;
            }
            set
            {
                this.gridSizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Rows")]
        public List<RoomTileGridsTileGridRows> Rows
        {
            get
            {
                return this.rowsField;
            }
            set
            {
                this.rowsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("IsActive")]
        public string IsActive
        {
            get
            {
                return this.isActiveField;
            }
            set
            {
                this.isActiveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("TileSet")]
        public string TileSet
        {
            get
            {
                return this.tileSetField;
            }
            set
            {
                this.tileSetField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RoomTileGridsTileGridRows
    {

        private List<RoomTileGridsTileGridRowsRow> row;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Row")]
        public List<RoomTileGridsTileGridRowsRow> Row
        {
            get
            {
                return this.row;
            }
            set
            {
                this.row = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RoomTileGridsTileGridGridSize
    {

        private string widthField;

        private string heightField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Width")]
        public string Width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Height")]
        public string Height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RoomTileGridsTileGridRowsRow
    {

        private string tilesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Tiles")]
        public string Tiles
        {
            get
            {
                return this.tilesField;
            }
            set
            {
                this.tilesField = value;
            }
        }
    }
    #endregion

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RoomObject
    {

        private RoomObjectItem[] roomObjectItems;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Door")]
        [System.Xml.Serialization.XmlElementAttribute("Collectible")]
        [System.Xml.Serialization.XmlElementAttribute("Obstacle")]
        [System.Xml.Serialization.XmlElementAttribute("Director")]
        [System.Xml.Serialization.XmlElementAttribute("SpawnPoint")]
        [System.Xml.Serialization.XmlElementAttribute("Speaker")]
        [System.Xml.Serialization.XmlElementAttribute("MusicPoint")]
        [System.Xml.Serialization.XmlElementAttribute("Switch")]
        [System.Xml.Serialization.XmlElementAttribute("Enemy")]
        [XmlChoiceIdentifier("ObjectTypeArray")]
        public RoomObjectItem[] RoomObjectItems
        {
            get
            {
                return this.roomObjectItems;
            }
            set
            {
                this.roomObjectItems = value;
            }
        }

        [XmlIgnore]
        public ObjectTypes[] ObjectTypeArray;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RoomObjectItem
    {

        private List<GridPosition> gridPositionField;

        private List<RoomTarget> targetField;

        private List<Conversations> conversationsField;

        private List<TemplateMovementProvider> movementProviderField;

        private Conditions[] conditionsField;

        private string nameField;

        private string templateField;

        private bool isValidRespawnLocationField = true;

        private string switchObject;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SwitchObject
        {
            get
            {
                return this.switchObject;
            }
            set
            {
                this.switchObject = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GridPosition")]
        public List<GridPosition> GridPosition
        {
            get
            {
                return this.gridPositionField;
            }
            set
            {
                this.gridPositionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Target")]
        public List<RoomTarget> Target
        {
            get
            {
                return this.targetField;
            }
            set
            {
                this.targetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Name")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Template")]
        public string Template
        {
            get
            {
                return this.templateField;
            }
            set
            {
                this.templateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("IsValidRespawnLocation")]
        public bool IsValidRespawnLocation
        {
            get
            {
                return this.isValidRespawnLocationField;
            }
            set
            {
                this.isValidRespawnLocationField = value;
            }
        }        

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Conversations")]
        public List<Conversations> Conversations
        {
            get
            {
                return this.conversationsField;
            }
            set
            {
                this.conversationsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MovementProvider")]
        public List<TemplateMovementProvider> MovementProvider
        {
            get
            {
                return this.movementProviderField;
            }
            set
            {
                this.movementProviderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Conditions")]
        public Conditions[] Conditions
        {
            get
            {
                return this.conditionsField;
            }
            set
            {
                this.conditionsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RoomTarget
    {

        private string roomField;

        private string objectNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Room")]
        public string Room
        {
            get
            {
                return this.roomField;
            }
            set
            {
                this.roomField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("ObjectName")]
        public string ObjectName
        {
            get
            {
                return this.objectNameField;
            }
            set
            {
                this.objectNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class GridPosition
    {

        private string leftField;

        private string topField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Left")]
        public string Left
        {
            get
            {
                return this.leftField;
            }
            set
            {
                this.leftField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Top")]
        public string Top
        {
            get
            {
                return this.topField;
            }
            set
            {
                this.topField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Conditions
    {

        private List<ConditionsCondition> conditionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Condition")]
        public List<ConditionsCondition> Condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConditionsCondition
    {

        private string hasField;

        private string itemField;

        private string quantityField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Has")]
        public string Has
        {
            get
            {
                return this.hasField;
            }
            set
            {
                this.hasField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Item")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Quantity")]
        public string Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
    }



    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Conversations
    {

        private List<ConversationsConversation> conversation;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Conversation")]
        public List<ConversationsConversation> Conversation
        {
            get
            {
                return this.conversation;
            }
            set
            {
                this.conversation = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConversationsConversation
    {

        private List<Conditions> conditionsField;

        private List<Sentences> sentencesField;

        private List<Transactions> transactionsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Conditions")]
        public List<Conditions> Conditions
        {
            get
            {
                return this.conditionsField;
            }
            set
            {
                this.conditionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Sentences")]
        public List<Sentences> Sentences
        {
            get
            {
                return this.sentencesField;
            }
            set
            {
                this.sentencesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Transactions")]
        public List<Transactions> Transactions
        {
            get
            {
                return this.transactionsField;
            }
            set
            {
                this.transactionsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Sentences
    {

        private List<SentencesSentence> sentence;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Sentence")]
        public List<SentencesSentence> Sentence
        {
            get
            {
                return this.sentence;
            }
            set
            {
                this.sentence = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SentencesSentence
    {

        private string speakerField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Speaker")]
        public string Speaker
        {
            get
            {
                return this.speakerField;
            }
            set
            {
                this.speakerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Transactions
    {

        private List<TransactionsTransaction> transaction;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Transaction")]
        public List<TransactionsTransaction> Transaction
        {
            get
            {
                return this.transaction;
            }
            set
            {
                this.transaction = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TransactionsTransaction
    {

        private string typeField;

        private string itemField;

        private string quantityField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Type")]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Item")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Quantity")]
        public string Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
    }

    ///// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    //[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    //public partial class MovementProvider
    //{

    //    private List<Conditions> conditions;

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute("Conditions")]
    //    public List<Conditions> Conditions
    //    {
    //        get
    //        {
    //            return this.conditions;
    //        }
    //        set
    //        {
    //            this.conditions = value;
    //        }
    //    }
    //}


}