//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace OSATypes
{

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

	[System.Diagnostics.DebuggerStepThroughAttribute()]

	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class Visuals
	{

		private object[] itemsField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("Animations", typeof(VisualsAnimations), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[System.Xml.Serialization.XmlElementAttribute("Sprites", typeof(VisualsSprites), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public object[] Items
		{
			get
			{
				return this.itemsField;
			}
			set
			{
				this.itemsField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

	[System.Diagnostics.DebuggerStepThroughAttribute()]

	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class VisualsAnimations
	{

		private VisualsAnimationsAnimation[] animationField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("Animation", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public VisualsAnimationsAnimation[] Animation
		{
			get
			{
				return this.animationField;
			}
			set
			{
				this.animationField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

	[System.Diagnostics.DebuggerStepThroughAttribute()]

	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class VisualsAnimationsAnimation
	{

		private VisualsAnimationsAnimationDisplayOffset displayOffsetField;

		private VisualsAnimationsAnimationFrames framesField;

		private string nameField;

		private string typeField;

		private string spriteField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("DisplayOffset", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public VisualsAnimationsAnimationDisplayOffset DisplayOffset
		{
			get
			{
				return this.displayOffsetField;
			}
			set
			{
				this.displayOffsetField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("Frames")]
		public VisualsAnimationsAnimationFrames Frames
		{
			get
			{
				return this.framesField;
			}
			set
			{
				this.framesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Sprite
		{
			get
			{
				return this.spriteField;
			}
			set
			{
				this.spriteField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

	[System.Diagnostics.DebuggerStepThroughAttribute()]

	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class VisualsAnimationsAnimationFrames
	{

		private VisualsAnimationsAnimationFramesFrame[] framesField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("Frame", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public VisualsAnimationsAnimationFramesFrame[] Frame
		{
			get
			{
				return this.framesField;
			}
			set
			{
				this.framesField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

	[System.Diagnostics.DebuggerStepThroughAttribute()]

	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class VisualsAnimationsAnimationDisplayOffset
	{

		private string widthField;

		private string heightField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Width
		{
			get
			{
				return this.widthField;
			}
			set
			{
				this.widthField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Height
		{
			get
			{
				return this.heightField;
			}
			set
			{
				this.heightField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

	[System.Diagnostics.DebuggerStepThroughAttribute()]

	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class VisualsAnimationsAnimationFramesFrame
	{

		private string spriteField;

		private string durationField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Sprite
		{
			get
			{
				return this.spriteField;
			}
			set
			{
				this.spriteField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Duration
		{
			get
			{
				return this.durationField;
			}
			set
			{
				this.durationField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

	[System.Diagnostics.DebuggerStepThroughAttribute()]

	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class VisualsSprites
	{

		private VisualsSpritesSprite[] spriteField;

		private string textureField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("Sprite", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public VisualsSpritesSprite[] Sprite
		{
			get
			{
				return this.spriteField;
			}
			set
			{
				this.spriteField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Texture
		{
			get
			{
				return this.textureField;
			}
			set
			{
				this.textureField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

	[System.Diagnostics.DebuggerStepThroughAttribute()]

	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class VisualsSpritesSprite
	{

		private VisualsSpritesSpriteTextureRegion textureRegionField;

		private string nameField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("TextureRegion", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public VisualsSpritesSpriteTextureRegion TextureRegion
		{
			get
			{
				return this.textureRegionField;
			}
			set
			{
				this.textureRegionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

	[System.Diagnostics.DebuggerStepThroughAttribute()]

	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class VisualsSpritesSpriteTextureRegion
	{

		private string leftField;

		private string topField;

		private string widthField;

		private string heightField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Left
		{
			get
			{
				return this.leftField;
			}
			set
			{
				this.leftField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Top
		{
			get
			{
				return this.topField;
			}
			set
			{
				this.topField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Width
		{
			get
			{
				return this.widthField;
			}
			set
			{
				this.widthField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Height
		{
			get
			{
				return this.heightField;
			}
			set
			{
				this.heightField = value;
			}
		}
	}
}